import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
const TOTAL_ROUNDS=7,sizes=[4,6,8,10,12,14,16],directions=[[0,1],[1,0],[1,1],[1,-1]];
const emptyBoard=n=>Array.from({length:n},()=>Array(n).fill(null)),inside=(n,r,c)=>r>=0&&r<n&&c>=0&&c<n;
const lineKey=l=>l.map(([r,c])=>r+","+c).sort().join("|");
function findSOS(b,r,c){const n=b.length,h=[],seen=new Set(),add=l=>{const k=lineKey(l);if(!seen.has(k)){seen.add(k);h.push(l)}};for(const[dr,dc]of directions){if(b[r][c]==="O"){const a=[r-dr,c-dc],z=[r+dr,c+dc];if(inside(n,...a)&&inside(n,...z)&&b[a[0]][a[1]]==="S"&&b[z[0]][z[1]]==="S")add([a,[r,c],z])}else{const o=[r+dr,c+dc],z=[r+2*dr,c+2*dc],o2=[r-dr,c-dc],z2=[r-2*dr,c-2*dc];if(inside(n,...o)&&inside(n,...z)&&b[o[0]][o[1]]==="O"&&b[z[0]][z[1]]==="S")add([[r,c],o,z]);if(inside(n,...o2)&&inside(n,...z2)&&b[o2[0]][o2[1]]==="O"&&b[z2[0]][z2[1]]==="S")add([[r,c],o2,z2])}}return h}
function App(){
 const[screen,setScreen]=useState("home"),[names,setNames]=useState(["PLAYER 1","PLAYER 2"]),[round,setRound]=useState(1),[board,setBoard]=useState(emptyBoard(4)),[owners,setOwners]=useState(emptyBoard(4)),[scores,setScores]=useState([0,0]),[rs,setRs]=useState([0,0]),[turn,setTurn]=useState(0),[letter,setLetter]=useState("S"),[lines,setLines]=useState([]),[used,setUsed]=useState(new Set()),[winner,setWinner]=useState(null),[gameWinner,setGameWinner]=useState(null),[message,setMessage]=useState("");
 const n=sizes[round-1];
 const start=()=>{const x=names.map((v,i)=>v.trim()||"PLAYER "+(i+1));setNames(x);setRound(1);setBoard(emptyBoard(4));setOwners(emptyBoard(4));setScores([0,0]);setRs([0,0]);setTurn(0);setLetter("S");setLines([]);setUsed(new Set());setWinner(null);setGameWinner(null);setMessage("");setScreen("game")};
 const next=()=>{const r=round+1;setRound(r);setBoard(emptyBoard(sizes[r-1]));setOwners(emptyBoard(sizes[r-1]));setRs([0,0]);setTurn(0);setLetter("S");setLines([]);setUsed(new Set());setWinner(null);setMessage("")};
 const move=(r,c)=>{if(board[r][c]||winner!==null)return;const b=board.map(x=>x.slice()),o=owners.map(x=>x.slice());b[r][c]=letter;o[r][c]=turn;const fresh=findSOS(b,r,c).filter(l=>!used.has(lineKey(l))),u=new Set(used);fresh.forEach(l=>u.add(lineKey(l)));const gain=fresh.length,a=[...rs],s=[...scores];a[turn]+=gain;s[turn]+=gain;setBoard(b);setOwners(o);setUsed(u);setLines([...lines,...fresh.map(cells=>({cells,player:turn}))]);setRs(a);setScores(s);if(b.every(row=>row.every(Boolean))){const rw=a[0]===a[1]?"DRAW":a[0]>a[1]?0:1;setWinner(rw);if(round===TOTAL_ROUNDS)setGameWinner(s[0]===s[1]?"DRAW":s[0]>s[1]?0:1);return}setTurn(gain?turn:1-turn);setMessage(gain?names[turn]+" scored +"+gain+" SOS — play again!":"")};
 if(screen==="home")return <main className="screen home"><div className="brand">SOS<span>16</span><small>LOCAL TWO-PLAYER ARENA</small></div><div className="hero"><p className="tag">7 ROUND SHOWDOWN</p><h1>Make your <i>SOS.</i><br/>Own the board.</h1><p className="sub">Two players. One screen. 4×4 → 16×16.</p><input placeholder="PLAYER 1" value={names[0]} onChange={e=>setNames([e.target.value,names[1]])}/><input placeholder="PLAYER 2" value={names[1]} onChange={e=>setNames([names[0],e.target.value])}/><div className="buttons"><button onClick={start}>START MATCH</button></div></div></main>;
 if(screen==="result")return <main className="screen result"><div className="brand">SOS<span>16</span><small>FINAL RESULT</small></div><div className="resultCard"><p className="tag">7 ROUNDS COMPLETE</p><h1>{gameWinner==="DRAW"?"DRAW":names[gameWinner]+" WINS"}</h1><div className="finalScores"><div className="playerCard p1"><b>{names[0]}</b><strong>{scores[0]}</strong></div><div className="playerCard p2"><b>{names[1]}</b><strong>{scores[1]}</strong></div></div><button onClick={()=>setScreen("home")}>PLAY AGAIN</button></div></main>;
 return <main className="screen game"><div className="gameBar"><div className="brand mini">SOS<span>16</span><small>ROUND {round}/{TOTAL_ROUNDS} · {n}×{n}</small></div><div className="scores"><span className="p1Text">{names[0]} <b>{scores[0]}</b></span><span className="p2Text">{names[1]} <b>{scores[1]}</b></span></div><button className="ghost miniBtn" onClick={()=>setScreen("home")}>EXIT</button></div><div className="roundStrip"><span>ROUND {round}</span><span>{n}×{n} BOARD</span><span>{winner!==null?(winner==="DRAW"?"ROUND DRAW":names[winner]+" WINS ROUND"):message||("TURN: "+names[turn])}</span></div><div className="gameWrap"><aside><h3>PLAYERS</h3>{names.map((name,i)=><div className={"side p"+(i+1)+" "+(turn===i&&winner===null?"active":"")} key={i}><b>{name}</b><small>{rs[i]} THIS ROUND</small></div>)}<div className="status">{winner!==null?(round<TOTAL_ROUNDS?"ROUND OVER":"MATCH OVER"):names[turn]+"'S TURN"}</div><div className="rules">7 rounds<br/>4×4 → 16×16<br/>SOS = +1<br/>Score SOS → play again</div></aside><section className="play"><div className="board" style={{gridTemplateColumns:"repeat("+n+",1fr)"}}>{board.map((row,r)=>row.map((v,c)=><button key={r+"-"+c} className={"cell "+(v||"")+" p"+(owners[r][c]!==null?owners[r][c]+1:"")} disabled={!!v||winner!==null} onClick={()=>move(r,c)}>{v}</button>))}{lines.map(({cells,player},i)=>{const[a,_,z]=cells,left=(a[1]+.5)*100/n,top=(a[0]+.5)*100/n,dx=(z[1]-a[1])*100/n,dy=(z[0]-a[0])*100/n,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;return <span key={i} className={"sosLine p"+(player+1)} style={{left:left+"%",top:top+"%",width:len+"%",transform:"rotate("+angle+"deg)"}}/>})}</div>{winner===null&&<div className="picker"><button className={letter==="S"?"selected":""} onClick={()=>setLetter("S")}>S</button><button className={letter==="O"?"selected":""} onClick={()=>setLetter("O")}>O</button></div>}{winner!==null&&round<TOTAL_ROUNDS&&<button className="nextRound" onClick={next}>START ROUND {round+1} · {sizes[round]}×{sizes[round]}</button>}{winner!==null&&round===TOTAL_ROUNDS&&<button className="nextRound" onClick={()=>setScreen("result")}>VIEW FINAL RESULT</button>}</section></div></main>
}
createRoot(document.getElementById("root")).render(<App/>);